# Generated by Django 5.0.1 on 2024-02-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(default='XL', max_length=50),
        ),
    ]
