# Generated by Django 5.0.1 on 2024-02-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_size_ordereditem_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='size',
        ),
    ]
